In [1]:
from langchain_huggingface import HuggingFaceEmbeddings
from transformers import AutoTokenizer
import numpy as np

In [2]:
def cosine_similarity(A, B):
    return np.dot(A, B) / (np.linalg.norm(A) * np.linalg.norm(B))

In [3]:
embedding_model = HuggingFaceEmbeddings(
                        #model_name="sentence-transformers/all-MiniLM-L12-v2",
                        model_name="sentence-transformers/all-mpnet-base-v2",
                        #model_kwargs=model_kwargs,
                        #encode_kwargs=encode_kwargs
                    )

In [4]:
tok = AutoTokenizer.from_pretrained(embedding_model.model_name)

In [5]:
model_max_length = tok.model_max_length
model_max_length

512

In [6]:
sentences = [
    "The bench press, revered as a foundational movement in power-lifting and bodybuilding, involves lying supine on a stable bench and driving a loaded barbell away from the chest under strict control, challenging both raw muscular strength and precise neuromuscular coordination across multiple joints.",
    "Before unracking the bar, an effective setup requires retracting and depressing the scapulae, digging the upper back firmly into the pad, planting the feet flat with a slight knee bend, and creating a moderate lumbar arch that elevates the rib cage while preserving spinal integrity.",
    "During the eccentric phase the bar should travel in a smooth, vertical-ish path toward the lower sternum with the elbows tucked roughly forty-five degrees from the torso, an angle that optimizes pectoral engagement, spares the anterior shoulder capsule, and sets up an efficient press-back trajectory.",
    "Pausing the bar for a controlled beat on the chest—rather than bouncing—builds starting strength, encourages maximal tension throughout the entire kinetic chain, and aligns with competition standards that demand a motionless bar before the concentric drive begins.",
    "Sustainable progress hinges on intelligent programming that applies progressive overload, supplements the big lift with accessory work for triceps, upper-back, and rotator-cuff resilience, and integrates adequate sleep, nutrition, and mobility work to facilitate recovery between demanding pressing sessions."
]
full_text = " ".join(sentences)

In [7]:
full_text_2 = """Ein Zettelkatalog (oder Kartenkatalog) ist ein Bibliothekskatalog, der aus vielen Katalogkarten (oder Zetteln) besteht, wobei auf jedem Zettel genau eine der in der jeweiligen Bibliothek vorhandenen Publikationen angeführt ist und jede Publikation mindestens einen Zettel erhält. Die Zettel werden üblicherweise in extra dafür angefertigten Katalogkästen nach dem Alphabet geordnet aufbewahrt. Der Zettelkatalog, vom heute gebräuchlichen elektronischen Bibliothekskatalog verdrängt, ist in vereinzelten Bibliotheken noch in Gebrauch.

In der Regel führten die Bibliotheken mehrere Zettelkataloge nebeneinander, die nach verschiedenen Kriterien (Autorname, Schlagwort, Titel der Publikation) geordnet waren.

Der entscheidende Vorteil gegenüber dem Bandkatalog ist, dass zwischen zwei Zettel immer noch ein weiterer Zettel passt (zwischen zwei Einträge in einem Bandkatalog passt nur solange noch ein Eintrag, solange noch ein beschreibbarer Zwischenraum bleibt). Der Zettelkatalog ist also unbegrenzt erweiterbar. Es gibt Zettelkataloge mit losen Zetteln, hier kann der Bibliotheksbenutzer oder Bibliothekar den gefundenen Zettel aus der Lade nehmen. Im anderen Fall sind die Zettel gelocht und mittels einer Lochstange im Katalogkasten fixiert. Die Zettel sind nicht frei herausnehmbar, wodurch die geordnete Reihenfolge gesichert werden soll. Farbige Leitkarten aus Pappe können das Ordnungsprinzip des jeweiligen Katalogs sichtbar machen.

Die anfangs noch handschriftlich oder mit Schreibmaschinen angefertigten Zettel wurden seit der Einführung der Elektronischen Datenverarbeitung durch ausgedruckte Zettelkarten verdrängt. Nach der Aufnahme einer Publikation in den elektronischen Katalog konnten beliebig viele Zettel der Publikation für die verschiedenen Zettelkataloge der Bibliothek ausgedruckt werden. Der Zettelkatalog ist heute nur noch in Bibliotheken in Funktion, die ihre Altbestände noch nicht anders erfasst haben. Ein Nachteil des Zettelkatalogs gegenüber dem OPAC ist, dass die Herstellung, Einordnung und Sortierung des Zettelkatalogs mit erheblichem Arbeitsaufwand verbunden ist. Auch sind Zettelkataloge ortsgebunden und benötigen oft viel Platz. Der Inhalt der meisten Zettelkataloge wurde deshalb mittlerweile mittels Retrokonversion digitalisiert und durch Retrokatalogisierung in OPACs übertragen.

Die Katalogkarten und Katalogschränke
Die Katalogkarten (oder Zettel) bestanden aus starkem Papier oder aus Karton. Die Größe der einzelnen Zettel beträgt seit 1948 – nach dem Internationalen Bibliotheksformat – meist genau 7,5 cm × 12,5 cm.

Die Katalogschränke (Zettelkasten) sind in der Regel 6 m × 6 m groß und mit Schubladen mit einer Kapazität von je 1000 bis 1200 Katalogkarten bestückt.

The bench press, revered as a foundational movement in power-lifting and bodybuilding, involves lying supine on a stable bench and driving a loaded barbell away from the chest under strict control, challenging both raw muscular strength and precise neuromuscular coordination across multiple joints.
"""


In [8]:
full_text_3 = """Ein Zettelkatalog (oder Kartenkatalog) ist ein Bibliothekskatalog, der aus vielen Katalogkarten (oder Zetteln) besteht, wobei auf jedem Zettel genau eine der in der jeweiligen Bibliothek vorhandenen Publikationen angeführt ist und jede Publikation mindestens einen Zettel erhält. Die Zettel werden üblicherweise in extra dafür angefertigten Katalogkästen nach dem Alphabet geordnet aufbewahrt. Der Zettelkatalog, vom heute gebräuchlichen elektronischen Bibliothekskatalog verdrängt, ist in vereinzelten Bibliotheken noch in Gebrauch.

In der Regel führten die Bibliotheken mehrere Zettelkataloge nebeneinander, die nach verschiedenen Kriterien (Autorname, Schlagwort, Titel der Publikation) geordnet waren.

Der entscheidende Vorteil gegenüber dem Bandkatalog ist, dass zwischen zwei Zettel immer noch ein weiterer Zettel passt (zwischen zwei Einträge in einem Bandkatalog passt nur solange noch ein Eintrag, solange noch ein beschreibbarer Zwischenraum bleibt). Der Zettelkatalog ist also unbegrenzt erweiterbar. Es gibt Zettelkataloge mit losen Zetteln, hier kann der Bibliotheksbenutzer oder Bibliothekar den gefundenen Zettel aus der Lade nehmen. Im anderen Fall sind die Zettel gelocht und mittels einer Lochstange im Katalogkasten fixiert. Die Zettel sind nicht frei herausnehmbar, wodurch die geordnete Reihenfolge gesichert werden soll. Farbige Leitkarten aus Pappe können das Ordnungsprinzip des jeweiligen Katalogs sichtbar machen.

Die anfangs noch handschriftlich oder mit Schreibmaschinen angefertigten Zettel wurden seit der Einführung der Elektronischen Datenverarbeitung durch ausgedruckte Zettelkarten verdrängt. Nach der Aufnahme einer Publikation in den elektronischen Katalog konnten beliebig viele Zettel der Publikation für die verschiedenen Zettelkataloge der Bibliothek ausgedruckt werden. Der Zettelkatalog ist heute nur noch in Bibliotheken in Funktion, die ihre Altbestände noch nicht anders erfasst haben. Ein Nachteil des Zettelkatalogs gegenüber dem OPAC ist, dass die Herstellung, Einordnung und Sortierung des Zettelkatalogs mit erheblichem Arbeitsaufwand verbunden ist. Auch sind Zettelkataloge ortsgebunden und benötigen oft viel Platz. Der Inhalt der meisten Zettelkataloge wurde deshalb mittlerweile mittels Retrokonversion digitalisiert und durch Retrokatalogisierung in OPACs übertragen.

Die Katalogkarten und Katalogschränke
Die Katalogkarten (oder Zettel) bestanden aus starkem Papier oder aus Karton. Die Größe der einzelnen Zettel beträgt seit 1948 – nach dem Internationalen Bibliotheksformat – meist genau 7,5 cm × 12,5 cm.

Die Katalogschränke (Zettelkasten) sind in der Regel 6 m × 6 m groß und mit Schubladen mit einer Kapazität von je 1000 bis 1200 Katalogkarten bestückt.
"""


In [9]:
len(full_text)

1459

In [10]:
embeddings_full_text = embedding_model.embed_documents([full_text])
len(embeddings_full_text)

1

In [11]:
chunks = []
i = 0
while i < len(full_text):
    chunks.append(full_text[i:i+model_max_length]) 
    i += model_max_length

In [12]:
[len(chunk) for chunk in chunks]

[512, 512, 435]

In [13]:
chunks_embeddings = embedding_model.embed_documents(chunks)

In [14]:
chunks_embeddings = np.array(chunks_embeddings)
chunks_embeddings.shape

(3, 768)

In [15]:
chunks_embeddings = chunks_embeddings.sum(axis=0)*(1/3)
chunks_embeddings.shape

(768,)

In [16]:
cosine_similarity(embeddings_full_text, np.array(embeddings_trunc_text).T)

NameError: name 'embeddings_trunc_text' is not defined

In [ ]:
cosine_similarity(chunks_embeddings, np.array(embeddings_trunc_text).T)

array([0.04001066])

In [ ]:
cosine_similarity(embeddings_full_text, np.array(chunks_embeddings).T)

array([0.89283136])

### Use Tokenizer

In [ ]:
chunks = list(token_split_tokens(full_text))
chunks

['<s> the bench press, revered as a foundational movement in power - lifting and bodybuilding, involves lying supine on a stable bench and driving a loaded barbell away from the chest under strict control, challenging both raw muscular strength and precise neuromuscular coordination across multiple joints. before unracking the bar, an effective setup requires retracting and depressing the scapulae, digging the upper back firmly into the pad, planting the feet flat with a slight knee bend, and creating a moderate lumbar arch that elevates the rib cage while preserving spinal integrity. during the eccentric phase the bar should travel in a smooth, vertical - ish path toward the lower sternum with the elbows tucked roughly forty - five degrees from the torso, an angle that optimizes pectoral engagement, spares the anterior shoulder capsule, and sets up an efficient press - back trajectory. pausing the bar for a controlled beat on the chest — rather than bouncing — builds starting strength

In [ ]:
len(full_text)

1459

In [ ]:
tks = tok.tokenize(full_text, add_special_tokens=False)
len(tks)

283

In [ ]:
len(chunks[0])

1484

In [ ]:
vectors = embedding_model.embed_documents(chunks)

In [ ]:
cosine_similarity(embeddings_full_text, np.array(vectors).T)

array([[0.99486526]])

In [ ]:
cosine_similarity(embeddings_full_text, np.array(vectors[0]).T)


array([0.99486526])

In [19]:
embeddings_trunc_text = embedding_model.embed_documents([full_text[:model_max_length]])
embeddings_trunc_text = embedding_model.embed_documents([full_text[:model_max_length]])

In [20]:
def token_split_tokens(text, max_len=model_max_length, overlap=40):
    tks = tok.tokenize(text, add_special_tokens=False)
    for i in range(0, len(tks), max_len - overlap - 2):  # reserve 2 spots
        sub = tks[i : i + max_len - 2]
        ids = [tok.cls_token_id] + tok.convert_tokens_to_ids(sub) + [tok.sep_token_id]
        yield tok.decode(ids)            # or return the ids directly

In [42]:
def embed_document(embedding_model, text): 
    chunks = list(token_split_tokens(text))
    vectors = np.array(embedding_model.embed_documents(chunks))
    print(vectors.shape)
    return np.array([vectors.mean(axis=0)])

In [22]:
e1 = embed_document(embedding_model, full_text)
e1.shape

(1, 768)

In [23]:
e2 = embed_document(embedding_model, full_text_2)
e2.shape

Token indices sequence length is longer than the specified maximum sequence length for this model (989 > 512). Running this sequence through the model will result in indexing errors


(1, 768)

In [24]:
e3 = embed_document(embedding_model, full_text_3)
e3.shape

(1, 768)

In [25]:
cosine_similarity(e1,e2.T)

array([[0.33369933]])

In [26]:
cosine_similarity(e1,e3.T)

array([[0.00236089]])

In [27]:
e2_b = np.array(embedding_model.embed_documents([full_text_2]))

In [28]:
cosine_similarity(e1,e2_b.T)

array([[-0.00305396]])

In [43]:
a = embed_document(embedding_model, "Hallo")

(1, 768)


In [44]:
b = embedding_model.embed_documents(["Hallo"])

In [45]:
a.shape, np.array(b).shape

((1, 768), (1, 768))

In [46]:
cosine_similarity(a,np.array(b).T)

array([[0.89732082]])